log_name,conversation_length,visible_transitions_ground_truth,visible_transitions_generated,shared_activities,,num_it,,error history
01.txt,2,8,8,8,1.970344067,1,,
02.txt,22,16,56,16,205.1306663,11,,
03.txt,2,11,11,11,8.655744553,1,,
04.txt,2,10,10,10,5.206332684,1,,
05.txt,4,11,23,11,17.67085361,2,,
06.txt,2,10,10,10,6.824796438,1,,
07.txt,22,13,17,13,163.7873571,11,,
08.txt,2,12,12,12,5.004754066,1,,
09.txt,8,13,21,13,47.28155351,4,,
10.txt,10,9,12,9,39.48326039,5,,
11.txt,2,12,13,10,5.356916428,1,,
12.txt,6,10,12,10,24.04219365,3,,
13.txt,6,9,11,9,17.55832767,3,,
14.txt,2,10,10,10,3.035303593,1,,
15.txt,2,10,10,10,3.240731001,1,,
16.txt,2,24,24,24,14.38944936,1,,
17.txt,10,25,26,20,93.87185311,5,,
18.txt,Error,26,None,None,264.3560934,#VALUE!,,"open-mixtral-8x22b failed to fix the errors after 15 iterations! This is the error history: ['The transitive closure of the provided relation violates irreflexivity!', 'The transitive closure of the provided relation violates irreflexivity!', 'Error occurred at line 2: \final_model = gen.partial_order(\"" with message: NameError: name \\'gen\\' is not defined', 'Error occurred at line 11: \""        (submit_application, review_application_and_documents),\"" with message: NameError: name \\'submit_application\\' is not defined', 'Error occurred at line 49: \""final_model = gen.partial_order(\"" with message: Exception: Ensure that each submodel is used uniquely! Avoid trying to reuse submodels that were used as children of other constructs (xor, loop, or partial_order) before! The error occured when trying to reuse a node of type Activity (Begin attending classes).', 'Error occurred at line 11: \""        (submit_application, review_application_and_documents),\"" with message: NameError: name \\'submit_application\\' is not defined', 'The transitive closure of the provided relation violates irreflexivity!', 'Error occurred at line 11: \""        (submit_application, review_application_and_documents),\"" with message: NameError: name \\'submit_application\\' is not defined', 'Error occurred at line 74: \""appeals_loop = gen.loop(do=file_an_appeal, redo=begin_attending_classes_and_add_drop_courses)\"" with message: Exception: Ensure that each submodel is used uniquely! Avoid trying to reuse submodels that were used as children of other constructs (xor, loop, or partial_order) before! The error occured when trying to reuse a node of type PartialOrder.', 'Error occurred at line 9: \""appeals_loop = gen.loop(do=file_an_appeal, redo=begin_attending_classes_and_add_drop_courses.copy())  # Create a copy of the subprocess\"" with message: NameError: name \\'file_an_appeal\\' is not defined', 'Error occurred at line 9: \""appeals_loop = gen.loop(do=file_an_appeal.copy(), redo=begin_attending_classes_and_add_drop_courses.copy())  # Create a copy of the subprocesses\"" with message: NameError: name \\'file_an_appeal\\' is not defined', 'Error occurred at line 9: \""file_an_appeal_copy = file_an_appeal.copy()\"" with message: NameError: name \\'file_an_appeal\\' is not defined', 'Error occurred at line 9: \""file_an_appeal_copy = file_an_appeal.copy()\"" with message: NameError: name \\'file_an_appeal\\' is not defined', 'Error occurred at line 9: \""file_an_appeal_copy = gen.partial_order(dependencies=[(submit_appeal_form.copy(), meet_appeals_committee.copy()), (meet_appeals_committee.copy(), await_decision.copy())])\"" with message: NameError: name \\'submit_appeal_form\\' is not defined', 'Error occurred at line 9: \""submit_appeal_form_copy = submit_appeal_form.copy()\"" with message: NameError: name \\'submit_appeal_form\\' is not defined']"""
order.txt,6,8,10,8,22.06827927,3,,
hotel.txt,2,13,13,12,8.662495852,1,,
